### PR TITLE
RequestMethodInterface 

### PR DESCRIPTION
**Pull request by KpuTuK**
Example:

```php
<?php
class Request extends ServerRequest implements
    RequestInterface, RequestMethodInterface 
{
    public function __construct(
        $uri = '/',
        $method = Request::METHOD_GET,
        array $server = array(), 
        array $query = array(), 
        array $parsedBody = array(), 
        array $cookies = array(), 
        array $files = array()
    ) {
        //...
    }
}

$request = new Http\Request(
            '/', 
            Request::METHOD_GET,
            $GLOBALS['_SERVER'], 
            $GLOBALS['_GET'],
            $GLOBALS['_POST'],
            $GLOBALS['_COOKIE'], 
            $GLOBALS['_FILES']
        );
```

### CODE REVIEW

**Comment by weierophinney** [comment]
I like this idea a lot, but am asking @php-fig/secretaries and other PSR authors if we can include convenience code not defined in the PSR but within the same scope. It looks like we'd likely need to create a util repo, such as was done with php-fig/cache-util. If we do that, I'll ping you to make this PR against that one instead.

**Comment by michaelcullum** [comment]
As per IRC, I'm for having a utils repo. @weierophinney If you're :+1: on that then shall we proceed?

**Comment by weierophinney** [comment]
@KpuTuK We've now created a new repository, [http-message-util](https://github.com/php-fig/http-message-util]. Could you submit this pull request against that repository, please?

**Comment by weierophinney** [comment]
I was able to pull this in as a patch to http-message-util, keeping attribution. Thanks, @KpuTuK !

**Comment by KpuTuK** [comment]
Thank!

**Pull request closed without merging**
