### PR TITLE
Correct typo in PSR7-Usage.md

### PR DESCRIPTION
**Pull request by ghost**
Corrected

> $response is an object implementing Psr\Http\Message\RequestInterface

to

> $response is an object implementing Psr\Http\Message\ResponseInterface

### CODE REVIEW

**Comment by gabidj** [comment]
Thank you . I haven't noticed this .

**Review by gabidj — APPROVED** [review]

**Comment by mvc-dev** [comment]
@gabidj You are welcome. The typo correction was actually my first contribution to GitHub :-)

**Comment by kktsvetkov** [comment]
I just saw it too, nice work @mvc-dev

**Comment by mvc-dev** [comment]
> I just saw it too, nice work @mvc-dev

Thank you, @kktsvetkov.

**Comment by theiggs** [comment]
Why wasn't this merged? This is an obvious typo. :thinking:

**Pull request closed without merging**
